config/routes.rb
Rails.application.routes.draw do  
  get 'intentions/new_intention'
  get 'intentions/index'
  get '/entity' => 'entities#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'create_entity',to: 'entities#create_entity', via: :all
  #match 'create_entity_value',to: 'entities#create_entity_value', via: :post
  match 'delete_entity', to: 'entities#delete_entity', via: :delete
  match 'delete_entity_value', to: 'entities#delete_entity_value', via: :get
  match 'update_entity', to: 'entities#update_entity', via: :patch
  #match 'edit_value', to: 'entities#edit_value', via: :get
  match 'update_entity_value', to: 'entities#update_entity_value', via: :patch
  match 'entity_value', to: 'entities#show_info', via: :get
  match 'release_version', to: 'entities#release_version', via: :post
  match 'import_entity', to: 'entities#import_entity', via: :post
  match 'datatable_entity_keyword', to: 'entities#datatable_entity_keyword', via: :get
  resource :entity

  
  resource :exports
  get '/export' => 'exports#index'
  match 'datatable_exports', to: 'exports#datatable_exports', via: :get
  match 'download_exports',to: 'exports#download_exports', via: :post
  match 'create_exports',to: 'exports#create_exports', via: :post
  match 'revert_version_exports',to: 'exports#revert_version_exports', via: :post 

  match 'add_dictionary', to: 'dictionary#add_dictionary', via: :get
  match 'release_dictionary', to: 'dictionary#release_dictionary', via: :post
  match 'create_dictionary', to: 'dictionary#create_dictionary', via: :post
  match 'edit_dictionary', to: 'dictionary#edit_dictionary', via: :get
  match 'update_dictionary', to: 'dictionary#update_dictionary', via: :patch
  match 'delete_dictionary', to: 'dictionary#delete_dictionary', via: :get  
  get '/dictionary' => 'dictionary#index'
  match 'datatable_dictionary', to: 'dictionary#datatable_dictionary', via: :get

  get '/keyword' => 'keyword#index' 
  resource :keyword

  get '/amivoice_ai' => 'login_system#index'
  match '/api/auth_check', to: 'login_system#login', via: :get
  match 'login_auth', to: 'login_system#login_auth', via: :post
  match 'logout_auth', to: 'login_system#logout_auth', via: :delete
  match '/api/logout', to: 'login_system#logout_auth', via: :get
  match 'check_auth', to: 'login_system#check_auth', via: :post
  root :to => 'login_system#index' 
  
  get '/intentions' => 'intentions#index'
  resource :intentions
  match 'datatable_intention', to: 'intentions#datatable_intention', via: :get
 # match 'new_intention', to: 'intentions#new_intention', via: :get
  #match 'update_intention', to: 'intentions#update_intention', via: :put
  match 'delete_intentions', to: 'intentions#delete_intention', via: :delete
  match 'delete_select_intentions', to: 'intentions#delete_select_intention', via: :get
  match 'intention_value', to: 'intentions#show_info', via: :get
 # match 'new', to: 'intentions#new', via: :post
end

app/controllers/login_system_controller.rb
require 'openssl'
require 'base64'

class LoginSystemController < ApplicationController  
    
    $alg = 'aes-256-cbc'
    $key = 'AMI_VOICE_THAI_123_CHR_123456789'  ## 32 Characters
    $iv = '1016100150078914' ## 16 characters

    def index   
        if !session[:current_user_id].nil?
            return redirect_to intentions_path
        end 
    end 

    def login
        # TODO: Change it into db login or remove it
        if !params['username'].nil? && !params['password'].nil? 
             @username = params['username']
             @password = params['password']
             login_auth()
        else
            return redirect_to login_path
        end  
    end
    def login_auth 
        if !@username.nil? && !@password .nil?
        elsif !params[:from_login][:username].nil? && !params[:from_login][:password].nil? && !params[:from_login][:username].blank? && !params[:from_login][:password].blank?
            @username = params[:from_login][:username]
            @password = encrypt(params[:from_login][:password])
        else
            return redirect_to amivoice_ai_path, warning_login: ["username or password is empty!!!"]
        end 
        @result_database = User.find_by(login: @username, password: decrypt(@password)) 
        if @result_database.present? 
            session[:current_user_id] = @result_database.id
            redirect_to intentions_path
        else
            redirect_to amivoice_ai_path, warning_login: ["username or password is incorrect!!!"]
        end
    end
    def logout_auth 
        session.delete :current_user_id
        redirect_to amivoice_ai_path 
    end
    def check_auth
        username = params[:username] 
        result_user = User.find_by(login: username)
        result = 0
        result = encrypt(result_user.password) if result_user.present?   #encrypt(result_user.password)
        respond_to do |format|
            format.html { send_data result }
        end
    end 
    private
    def encrypt(des_text)
        des = OpenSSL::Cipher::Cipher.new($alg)
        des.encrypt
        des.key = $key
        des.iv = $iv 
        result = des.update(des_text)
        result << des.final
        return Base64.encode64 result
    end
    def decrypt(des_text)
        des = OpenSSL::Cipher::Cipher.new($alg)
        des.decrypt
        des.key = $key
        des.iv = $iv
        result = des.update(Base64.decode64(des_text))
        result << des.final
        return result
    end
end

app/helpers/login_system_helper.rb
module LoginSystemHelper
end

app/views/login_system/index.html.erb
<div class="mdl-grid full-width">
  <div class="mdl-cell mdl-cell--5-col">
    <div id="fill-username">
        <%= form_for :from_login, url: login_auth_path, method: :POST do |f| %> 
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="width:65%">
                <h6>Username</h6> 
                <%= f.text_field :username, class:"mdl-textfield__input", id:"username", maxlength: 100, :disabled => false %>  
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label password" style="width:65%">  
                <h6>Password</h6> 
                <%= f.password_field :password, class:"mdl-textfield__input", id:"password", maxlength: 100, :disabled => false %>

            </div>
                    
            <div class="mdl-grid">
                <div class="mdl-cell mdl-cell--2-col"></div>
                <div class="mdl-cell mdl-cell--10-col">
                    <%= f.submit "Login", class:"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored", style:"float:left;margin-left:30px;", :disabled => false %>
                </div>
            </div> 
        <% end %> 
    </div>
  </div>
  <div class="mdl-cell mdl-cell--7-col right-side">
    <div id="title_login">
        <h1 style="margin-bottom:0px;">AmiVoice AI Tools</h1>
        <hr style="align:center" id="line_login">
    </div>    
  </div>
</div>