config/routes.rb
Rails.application.routes.draw do  
  get 'intentions/new_intention'
  get 'intentions/index'
  get '/entity' => 'entities#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'create_entity',to: 'entities#create_entity', via: :all
  #match 'create_entity_value',to: 'entities#create_entity_value', via: :post
  match 'delete_entity', to: 'entities#delete_entity', via: :delete
  match 'delete_entity_value', to: 'entities#delete_entity_value', via: :get
  match 'update_entity', to: 'entities#update_entity', via: :patch
  #match 'edit_value', to: 'entities#edit_value', via: :get
  match 'update_entity_value', to: 'entities#update_entity_value', via: :patch
  match 'entity_value', to: 'entities#show_info', via: :get
  match 'release_version', to: 'entities#release_version', via: :post
  match 'import_entity', to: 'entities#import_entity', via: :post
  match 'datatable_entity_keyword', to: 'entities#datatable_entity_keyword', via: :get
  resource :entity

  
  resource :exports
  get '/export' => 'exports#index'
  match 'datatable_exports', to: 'exports#datatable_exports', via: :get
  match 'download_exports',to: 'exports#download_exports', via: :post
  match 'create_exports',to: 'exports#create_exports', via: :post
  match 'revert_version_exports',to: 'exports#revert_version_exports', via: :post 

  match 'add_dictionary', to: 'dictionary#add_dictionary', via: :get
  match 'release_dictionary', to: 'dictionary#release_dictionary', via: :post
  match 'create_dictionary', to: 'dictionary#create_dictionary', via: :post
  match 'edit_dictionary', to: 'dictionary#edit_dictionary', via: :get
  match 'update_dictionary', to: 'dictionary#update_dictionary', via: :patch
  match 'delete_dictionary', to: 'dictionary#delete_dictionary', via: :get  
  get '/dictionary' => 'dictionary#index'
  match 'datatable_dictionary', to: 'dictionary#datatable_dictionary', via: :get

  get '/keyword' => 'keyword#index' 
  resource :keyword

  get '/amivoice_ai' => 'login_system#index'
  match '/api/auth_check', to: 'login_system#login', via: :get
  match 'login_auth', to: 'login_system#login_auth', via: :post
  match 'logout_auth', to: 'login_system#logout_auth', via: :delete
  match '/api/logout', to: 'login_system#logout_auth', via: :get
  match 'check_auth', to: 'login_system#check_auth', via: :post
  root :to => 'login_system#index' 
  
  get '/intentions' => 'intentions#index'
  resource :intentions
  match 'datatable_intention', to: 'intentions#datatable_intention', via: :get
 # match 'new_intention', to: 'intentions#new_intention', via: :get
  #match 'update_intention', to: 'intentions#update_intention', via: :put
  match 'delete_intentions', to: 'intentions#delete_intention', via: :delete
  match 'delete_select_intentions', to: 'intentions#delete_select_intention', via: :get
  match 'intention_value', to: 'intentions#show_info', via: :get
 # match 'new', to: 'intentions#new', via: :post
end

app/models/intention.rb
class Intention < ApplicationRecord

    def self.select_all
       Intention.all
    end

    def self.find_intention intention_tag, intention_name, intention_code
        Intention.where("intention_tag = ? OR intention_name = ? OR  intention_code = ?" ,intention_tag, intention_name, intention_code)
    end

end

app/controllers/intentions_controller.rb
class IntentionsController < ApplicationController
  def index
    @intention = Intention.select_all
    return respond_to do |format| 
          format.html { render :index } 
          format.json { render json: IntentionDatatable.new(view_context)}
        end  
  end

  def new
     @@state = 'new'
     @intention = Intention.new
     @submit_bt = 'Add'
  end

  def edit
    @@state = 'edit'
     @intention = Intention.find(params[:id])
     @submit_bt = 'Update'
  end

  def create
    intention_name = params[:intention][:intention_name].downcase
    intention_tag = params[:intention][:intention_tag].downcase
    intention_code = params[:intention][:intention_code]
    check_dup_intention = Intention.find_intention(intention_tag, intention_name, intention_code) 
    if check_dup_intention.blank?
        @intention = Intention.create(intention_params)
        if @intention.save
         redirect_to action: 'new'
        else
          render 'new'
        end
    else
       flash[:danger] ||= []
       flash[:danger] << "Error: Duplicated Intention!!"
       redirect_to action: 'new'
    end 
    
      
  end

  def update
    @intention = Intention.find(params[:intention][:intention_id])
    
    if @intention.update(update_intention_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def delete_intention
    @intention = Intention.find(params[:id])
    @intention.destroy
    #redirect_back fallback_location: root_path
  end
  
  def delete_select_intention
    id = params[:id]  || [params[:select_delete].split(',')]
    @intention = Intention.find(id)
    @intention.each {|d| d.destroy} if id.instance_of? Array
    @intention.destroy if id.instance_of? String  
    redirect_back fallback_location: root_path
     
  end

    private def intention_params
      params[:intention][:created_by] = session[:current_user_id]
      params.require(:intention).permit(:intention_code, :intention_name, :intention_tag,:created_by)
    end

    private def update_intention_params
      params[:intention][:updated_by] = session[:current_user_id]
      params.require(:intention).permit(:intention_code, :intention_name, :intention_tag,:updated_by)
    end

end 

app/helpers/intentions_helper.rb
module IntentionsHelper
end

app/views/intentions/_form.html.erb
<%= form_for @intention, url: intentions_path do |f| %>
    <div class="mdl-grid">

        <div class="mdl-grid row">
      <div class="mdl-cell mdl-cell--1-col"></div>
      <div class="mdl-cell mdl-cell--2-col title">
        <h5>Intention Code:</h5>
      </div>
      <div class="mdl-cell mdl-cell--8-col textfield" id="textfield_intention">  
          <%= image_tag("asterisk.png", size: "8x8")%>
          <div class="mdl-textfield mdl-js-textfield" style = "width: 90%">
             <%= f.text_field :intention_code,  id:"txt_intention_code", class:"mdl-textfield__input", pattern:"-?[0-9]*(\.[0-9]+)?" , required: true, oninvalid:"setCustomValidity('Enter intention code only number.')",onchange:"try{setCustomValidity('')}catch(e){}", maxlength: 10, size: 200 %> 
              <label class = "mdl-textfield__label" for = "txt_intention_code"></label>
          </div>
      </div>
      <div class="mdl-cell mdl-cell--1-col"> </div>
    </div>

    <div class="mdl-grid row">
      <div class="mdl-cell mdl-cell--1-col"></div>
      <div class="mdl-cell mdl-cell--2-col title">
        <h5>Intention Tag:</h5>
      </div>
      <div class="mdl-cell mdl-cell--8-col textfield" id="textfield_intention">  
          <%= image_tag("asterisk.png", size: "8x8")%>
          <div class="mdl-textfield mdl-js-textfield" style = "width: 90%">
            <%= f.text_field :intention_tag,  id:"txt_intention_tag", class:"mdl-textfield__input", required: true, onchange:"validate_intention()", maxlength: 100, size: 200 %>
            <label class="mdl-textfield__label" for="sample3"></label>
          </div>
      </div>
      <div class="mdl-cell mdl-cell--1-col"> </div>
    </div>
    <div class="mdl-grid row">  
      <div class="mdl-cell mdl-cell--1-col"></div>
      <div class="mdl-cell mdl-cell--2-col title">
        <h5>Intention Name: </h5>
      </div>
      <div class="mdl-cell mdl-cell--8-col textfield" id="textfield_intention"> 
          <%= image_tag("asterisk.png", size: "8x8")%>
          <div class="mdl-textfield mdl-js-textfield" style = "width: 90%">
            <%= f.text_field :intention_name,  id:"txt_intention_name", class:"mdl-textfield__input", required: true, onchange:"validate_intention()", maxlength: 200 %>
            <label class="mdl-textfield__label" for="sample3"></label>
          </div>
          <div>  <%= f.hidden_field :intention_id, :value => params[:id], id:"txt_intention_id" %> </div>
          <div class="mdl-grid" style="float: right;" >
             <%= f.submit @submit_bt, class:"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored", id:"btn_submit" %>  
          </div>
      </div>
      <div class="mdl-cell mdl-cell--1-col"> </div>
    </div>
  



    </div>    
    <% end %>

app/views/intentions/_intention_table.html.erb
  <%= content_tag :table, class: "display compact table_intention", style:"width:100%", data: { url: intentions_path(format: :json)} do %>
  
    <thead>
    <tr id="header_table">
    <th><%= button_tag onclick:"checkbox_intention_datatable()", id:"btn_delete_selected" do %><i class="material-icons" id="delete_all" style="visibility:hidden">delete_outline</i><% end %>
      <div class="mdl-tooltip mdl-tooltip--large" for="delete_all"><span id="count-checked-checkboxes"></span> Selected(s)</div></th>
      <th class="mdl-data-table__cell--non-numeric" width="20%" id="head_table">Intention Code</th>
      <th class="mdl-data-table__cell--non-numeric" width="25%" id="head_table">Intention Name</th>
      <th class="mdl-data-table__cell--non-numeric" width="25%" id="head_table">Intention Tag</th>
      <th class="mdl-data-table__cell--non-numeric" width="20%">Last updated</th>
      <th width="10%">Action</th>
    </tr>
    </thead>
    <tbody>
    
    </tbody>
<% end %>

 <script>
$("#test").click(function(){
    var reg = $('#test2').val();
    $(".table_intention").DataTable().search(reg,true,true, true,true).draw();
});

  $(document).ready(function() {
  
    $("#btn_submit").click(function(){
    var $form = $('#delete_select').closest('form');
    $form.find('#btn_delete_selected').click();
    });
  });

</script>

app/views/intentions/edit.html.erb
<% is_user_logged_in? %>


<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
<!--------- HEAD --------->
    <div class="mdl-grid ">
      <div class="mdl-cell mdl-cell--12-col">
        <h4>Edit Intention</h4> 
      </div>
    </div>  
    <hr>
<!------------- Form -------------->
  <%= render 'form' %>

<!--------- DATA TABLE --------->
     <hr>  
     <div>
       <%= render 'intention_table' %>
    </div>

  </div>
</div>

app/views/intentions/index.html.erb
<% is_user_logged_in? %>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <div class="mdl-grid">
      <div class="mdl-cell mdl-cell--11-col">
        <h4>Intention List</h4> 
      </div>
      <div class="mdl-cell mdl-cell--1-col" style = "display:block">
      <%= link_to new_intentions_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored", style:"width: 111px" do%>+ Add Intention <% end %>
      
      </div>
    </div>   
    <hr>  
     <%= render 'intention_table' %>
  
  </div> 
</div> 
  

app/views/intentions/new.html.erb
<% is_user_logged_in? %>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
<!--------- HEAD --------->
    <div class="mdl-grid ">
      <div class="mdl-cell mdl-cell--12-col">
        <h4>New Intention</h4> 
      </div>
    </div>  
    <hr>
<!------------- Form -------------->
    <%= render 'form' %>
<!--------- DATA TABLE --------->
     <hr>  
     <div>
       <%= render 'intention_table' %>
    </div>

  </div>
</div>